### PR TITLE
Update communityNodes.json

### PR DESCRIPTION
**Pull request by tash22ka**
Would appreciate adding my node 'Lone Star Node' to the leasing list. Best, Tash!

### CODE REVIEW

**Review by jasny — CHANGES_REQUESTED** [review]
@tash22ka Please make sure the modified JSON is valid: https://jsonlint.com/

**Comment by tash22ka** [comment]
> @tash22ka Please make sure the modified JSON is valid: https://jsonlint.com/

Done!

**Comment by jasny** [comment]
> > @tash22ka Please make sure the modified JSON is valid: https://jsonlint.com/
> 
> Done!

It's not done. The json is still broken and Travis is still failing. Please use jsonlint or a similar tool to check that the modified json file is correct.

**Comment by tash22ka** [comment]
Weird even though I double checked on the link you provided. 

Will give it another try tonight. 

Thanks!

**Review by jasny — CHANGES_REQUESTED** [review]
Only add your node. Do not change the whole formatting of the file.

**Comment by jasny** [comment]
I'll add it manually.Geez

**Comment by tash22ka** [comment]
No need for Geez, thank you anyways.

**Pull request closed without merging**
